/**********************************************
 * This code was generated by ksolve++ v1.0.0 *
 **********************************************/

#ifndef SCRAMBLE_H
#define SCRAMBLE_H

class Scramble{
public:
    std::string name;
    Puzzle *state;
    int startDepth;
    int maxDepth;
    int slack;
    int maxSolutions;
};

#endif // SCRAMBLE_H
